export default {



	APPLICATION_STATE: 'APPLICATION_STATE',

    ZONES_RECEIVED: 'ZONES_RECEIVED',

    ZONE_CREATED: 'ZONE_CREATED',

    COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',

    COMMENT_CREATED: 'COMMENT_CREATED',

    SELECT_ZONE: 'SELECT_ZONE',

    CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',

    PROFILE_RECEIVED: 'PROFILE_RECEIVED',

    PROFILE_UPDATED: 'PROFILE_UPDATED'

    // COMMENT_UPDATED: 'COMMENT_UPDATED'

    // LOGOUT: 'LOGOUT'

}