export default {

    ZONES_RECEIVED: 'ZONES_RECEIVED',

    ZONE_CREATED: 'ZONE_CREATED',

    COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',

    COMMENT_CREATED: 'COMMENT_CREATED',

    SELECT_ZONE: 'SELECT_ZONE',

    CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED'

    // PROFILE_CREATED: 'PROFILE_CREATED'

    // LOGOUT: 'LOGOUT'

}